import Head from 'next/head'

import { Inter } from '@next/font/google'

import Header from '../components/Header'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Smallcard from '../components/Smallcard'
import Largecard from '../components/Largecard'
import Mediumcard from '../components/Mediumcard'
import Partner from '../components/Partner'
import { signIn } from 'next-auth/react'


const inter = Inter({ subsets: ['latin'] })

export default function Home({small,view,partners}) {
  return (
    <div>
      <Head>
        <title>SleepHere</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Banner/>
      <main className=" bg-gray-100 ">
      
  
      <div className='text-3xl font-semibold p-3'>Available Accomodations</div>
      <section className='max-w-screen-lg mx-auto  grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 '>
        {small?.map(({img,location,distance})=>(
          <Smallcard key={img} img={img} location={location} distance={distance}/>
        ))}
      </section>
      <section className='bg-green-400 rounded-lg ml-4'>
        < div className='bg-white text-center m-10 pt-7 pb-3'>
          <p className='text-3xl font-serif'>Ready to experience the best?</p>
          <div className='flex space-x-4 '>
            <button className='bg-green-200 flex-grow rounded-r-lg font-semibold' onClick={signIn}>Sign-In</button>
          <button className='bg-green-300 flex-grow rounded-l-lg font-semibold'>Sign-up</button>
          </div>
          
        
        </div>
       </section>
     
       
    <div className='text-3xl font-bold p-3'>Explore 🇬🇭  </div>
      <section className='flex space-x-5 ml-4'>
        
        {/* medium */}
        {view?.map(({view,img})=>(
        <Mediumcard 
        key={img}
        view={view}
        img={img}
        />))}

      </section>
        
       
        <div className="min-h-[10px]">
          <Largecard/>
        </div> 
       
      
        
     
      <div className='text-3xl font-bold text-center pb-4 mt-4'>Partners</div>
      <div className='flex mx-4 pb-4 space-x-2'>
        {partners?.map(({brand})=>(
          <Partner key={brand} img={brand}/>
        ))}
      </div>
      <section>

      </section>

       
      </main>
<Footer/>
    </div>
  )
}
 export async function getStaticProps(){
  
const small = await fetch("https://www.jsonkeeper.com/b/XJ3K").then((res)=>res.json());
 const view =await fetch ("https://www.jsonkeeper.com/b/H7XX").then((res)=>res.json());
  const partners = await fetch ("https://www.jsonkeeper.com/b/CZH4").then((res)=>res.json());
return{
  props:{small,view,partners}
}
 }