import Head from 'next/head'

import { Inter } from '@next/font/google'

import Header from '../components/Header'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Smallcard from '../components/Smallcard'
import Largecard from '../components/Largecard'
import Mediumcard from '../components/Mediumcard'


const inter = Inter({ subsets: ['latin'] })

export default function Home({small}) {
  return (
    <div>
      <Head>
        <title>SleepHere</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Banner/>
      <main className=" bg-gray-100 ">
      
  
      
      <section>
        {small?.map(({img,location,distance})=>(
          <Smallcard key={img} img={img} location={location} distance={distance}/>
        ))}
      </section>
      <section>
        {/* large */}
        <Largecard/>
      </section>
      <section>
        {/* medium */}
        <Mediumcard/>
      </section>

       
      </main>
<Footer/>
    </div>
  )
}
 export async function getStaticProps(){
  
const small = await fetch("https://www.jsonkeeper.com/b/XJ3K").then((res)=>res.json());

return{
  props:{small}
}
 }